=== beardeddragon5/internettechnologie/praktikum2/bpml.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!NOTATION JPEG PUBLIC "JPEG Image Format">
<!NOTATION GIF PUBLIC "GIF Image Format">
<!ENTITY Foto SYSTEM 'dkajfjdsaf' NDATA JPEG>

<!ENTITY % StringElem "(#PCDATA)">
<!ENTITY % StringAttr "CDATA">
<!ENTITY AT "&#x040;">

<!ELEMENT Name %StringElem;>
<!ELEMENT Adresse %StringElem;>

<!ELEMENT Preisuebersicht (Tankstelle+, Paechter+, Mineraloelgesellschaft*, Options?)>
  <!ATTLIST Preisuebersicht datum %StringAttr; #REQUIRED>

  <!ELEMENT Tankstelle (Name, Adresse, Geodaten?, Beschreibung?, Preise)>
    <!ATTLIST Tankstelle paechter IDREF #REQUIRED>
    <!ATTLIST Tankstelle mineraloelgesellschaft IDREF #REQUIRED>
    <!ATTLIST Tankstelle bewertung (1|2|3|4|5|6) #IMPLIED>
    <!ATTLIST Tankstelle foto ENTITY #IMPLIED>

    <!ELEMENT Geodaten (Laengengrad, Breitengrad)>
      <!ELEMENT Laengengrad %StringElem;>
      <!ELEMENT Breitengrad %StringElem;>

    <!ELEMENT Beschreibung %StringElem;>
    <!ELEMENT Preise (Preis+)>
      <!ELEMENT Preis %StringElem;>
        <!ATTLIST Preis kraftstoffart (E10|Super|Diesel|SuperPlus) #REQUIRED>

  <!ELEMENT Paechter (#PCDATA|Name|Adresse)*>
    <!ATTLIST Paechter id ID #REQUIRED>

  <!ELEMENT Mineraloelgesellschaft (Name, Adresse, Email)>
    <!ATTLIST Mineraloelgesellschaft id ID #REQUIRED>
    <!ELEMENT Email %StringElem;>

  <!ELEMENT Options ANY>

=== beardeddragon5/internettechnologie/praktikum2/aufgabe1.xml
<!DOCTYPE Preisuebersicht SYSTEM "bpml.dtd">
<Preisuebersicht datum="01.01.2001">
  <Tankstelle paechter="p1" mineraloelgesellschaft="mg1" bewertung="3" foto="Foto">
    <Name>dajsfjdsa</Name>
    <Adresse>djsakf</Adresse>
    <Geodaten>
      <Laengengrad>123</Laengengrad>
      <Breitengrad>123</Breitengrad>
    </Geodaten>
    <Beschreibung>Best</Beschreibung>
    <Preise>
      <Preis kraftstoffart="E10">10</Preis>
      <Preis kraftstoffart="Super">120</Preis>
      <Preis kraftstoffart="Diesel">1233</Preis>
    </Preise>
  </Tankstelle>
  <Tankstelle paechter="p1" mineraloelgesellschaft="mg1">
    <Name>dajsfjdsa</Name>
    <Adresse>djsakf</Adresse>
    <Preise>
      <Preis kraftstoffart="SuperPlus">10</Preis>
    </Preise>
  </Tankstelle>
  <Paechter id="p1">
    <Name>Hallo</Name>
    <Adresse>kdsajfds</Adresse>
  </Paechter>
  <Mineraloelgesellschaft id="mg1">
    <Name>superland</Name>
    <Adresse>superstraÃŸe</Adresse>
    <Email>mega&AT;super.de</Email>
  </Mineraloelgesellschaft>
</Preisuebersicht>
