=== beardeddragon5/internettechnologie/praktikum2/vml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    targetNamespace="http://xml.netbeans.org/schema/Vorlesung"
    xmlns:vml="http://xml.netbeans.org/schema/Vorlesung">

  <xsd:simpleType name="Prozent">
    <xsd:restriction base="xsd:decimal">
      <xsd:minInclusive value="0"/>
      <xsd:maxInclusive value="100"/>
      <xsd:fractionDigits value="2" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="Wahl">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Wahltag" type="xsd:date" />
        <xsd:element name="Wahlbeginn" type="xsd:time" />
        <xsd:element name="Wahlende" type="xsd:time" />
        <xsd:element name="Partei" minOccurs="2" maxOccurs="100">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Name" type="xsd:string"/>
              <xsd:element name="Kandidat" minOccurs="3" maxOccurs="25">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Name" type="xsd:string"/>
                    <xsd:element name="Geburtsdatum" type="xsd:date"/>
                    <xsd:element name="Beruf" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Listenplatz" type="xsd:string"/>
                    <xsd:element name="Erststimmen" type="vml:Prozent" />
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="isBundesweit" type="xsd:boolean" />
            <xsd:attribute name="id" type="xsd:ID" />
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="Wahlergebnis">
          <xsd:complexType mixed="true">
            <xsd:sequence>
              <xsd:element name="Zweitstimme" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="vml:Prozent">
                      <xsd:attribute name="partei" type="xsd:IDREF" />
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute name="Wahltyp">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Landtagswahl"/>
            <xsd:enumeration value="Bundestagswahl"/>
            <xsd:enumeration value="Europawahl"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== beardeddragon5/internettechnologie/praktikum2/aufgabe2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Wahl Wahltyp="Landtagswahl" xmlns="http://xml.netbeans.org/schema/Vorlesung"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://xml.netbeans.org/schema/Vorlesung vml.xsd">
  <Wahltag>2002-09-24</Wahltag>
  <Wahlbeginn>09:00:00</Wahlbeginn>
  <Wahlende>09:00:00</Wahlende>
  <Partei isBundesweit="true" id="p1" >
    <Name>dsaf</Name>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
  </Partei>
  <Partei id="p2">
    <Name>dsaf</Name>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
    <Kandidat>
      <Name>dsaf</Name>
      <Geburtsdatum>2002-09-24</Geburtsdatum>
      <Beruf>dsaf</Beruf>
      <Listenplatz>dsaf</Listenplatz>
      <Erststimmen>10.00</Erststimmen>
    </Kandidat>
  </Partei>
  <Wahlergebnis>
    <Zweitstimme partei="p1">
      10.00
    </Zweitstimme>
    <Zweitstimme partei="p2">
      10.00
    </Zweitstimme>
  </Wahlergebnis>
</Wahl>
