=== beardeddragon5/internettechnologie/praktikum1/sml.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT Meisterschaft (Beginn, Ende, Mannschaft+, Spiel+)>
  <!ATTLIST Meisterschaft typ (EM|WM) #IMPLIED>

  <!ELEMENT Beginn (#PCDATA)>
  <!ELEMENT Ende (#PCDATA)>
  <!ELEMENT Mannschaft (Name, Land, Trainer, Spieler+, Erfolg*)>
    <!ATTLIST Mannschaft id ID #REQUIRED>

    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Land (#PCDATA)>
    <!ELEMENT Trainer (#PCDATA)>
    <!ELEMENT Spieler (#PCDATA)>
      <!ATTLIST Spieler position (Torwart|Verteidiger|Mittelfeld|Stuermer) #REQUIRED>
    <!ELEMENT Erfolg (#PCDATA|Titel|Jahr)*>
      <!ELEMENT Titel (#PCDATA)>
      <!ELEMENT Jahr (#PCDATA)>

  <!ELEMENT Spiel EMPTY>
    <!ATTLIST Spiel heim IDREF #REQUIRED>
    <!ATTLIST Spiel gast IDREF #REQUIRED>
    <!ATTLIST Spiel ergebnis CDATA #IMPLIED>

=== beardeddragon5/internettechnologie/praktikum1/aufgabe3.xml
<!DOCTYPE hh SYSTEM "sml.dtd">
<Meisterschaft typ="WM">
  <Beginn> 0.0.0 </Beginn>
  <Ende> 0.0.-10 </Ende>
  <Mannschaft id="man1">
    <Name> Menschen </Name>
    <Land> Ãœberall </Land>
    <Trainer> Das Land </Trainer>
    <Spieler position="Torwart">
      Mensch 1
    </Spieler>
    <Spieler position="Verteidiger">
      Mensch 2
    </Spieler>
  </Mannschaft>
  <Mannschaft id="man2">
    <Name> Aliens </Name>
    <Spieler position="Stuermer">
      Alien 1
    </Spieler>
    <Spieler position="Stuermer">
      Alien 2
    </Spieler>
    <Erfolg>
      <Jahr> 30 BC </Jahr> haben die Aliens die
      halbe Welt zerhÃ¶rt und tragen seit dem
      den Titel <Titel> Super Aliens </Titel>.
      Manche sagen verdient.
    </Erfolg>
  </Mannschaft>
  <Spiel heim="man1" gast="man2" ergebnis="aliens gewinnen" />
</Meisterschaft>

=== beardeddragon5/internettechnologie/praktikum1/aufgabe3_desc.xml
<!DOCTYPE hh SYSTEM "sml.dtd">
<Meisterschaft typ="EM">
  <Beginn> 0.0.0 </Beginn>
  <Ende> 0.0.-10 </Ende>
  <Mannschaft id="manschaft1">
    <Name> Gli Azzurri </Name>
    <Land> Italien </Land>
    <Trainer> Gatusso </Trainer>
    <Spieler position="Torwart">
     Buffon
    </Spieler>
    <Spieler position="Verteidiger">
      Barzagli
    </Spieler>
  </Mannschaft>
  <Mannschaft id="manschaft2">
    <Name> La Furia Roja </Name>
    <Land> Spanien </Land>
    <Spieler position="Stuermer">
      Costa
    </Spieler>
    <Spieler position="Mittelfeld">
      Fast garnichts
    </Spieler>
    <Erfolg>
      <Jahr> 30 BC </Jahr> haben die Spanier den Kontinet dominiert
      und haben jetzt den Titel <Titel> Super EMista</Titel>.

    </Erfolg>
  </Mannschaft>
  <Spiel heim="manschaft1" gast="manschaft2" ergebnis="Spanier gewinnen" />
</Meisterschaft>
