=== beardeddragon5/internettechnologie/praktikum1/vlml2.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--- Diese DTD beschreibt den Aufbau der MarkUp Language zur Vorlesungsbeschreibung -->
<!ELEMENT Vorlesung (Titel, Hochschule+, SWS, Semester, Kapitel+, Quelle+)>
  <!ELEMENT Titel (#PCDATA)>
  <!ELEMENT Hochschule (#PCDATA)>
  <!ELEMENT SWS (#PCDATA)>
  <!ELEMENT Semester (#PCDATA)>
  <!ELEMENT Kapitel (Name,Termin+)>
    <!ATTLIST Kapitel nummer CDATA #REQUIRED>
    <!ATTLIST Kapitel quelle IDREF #REQUIRED>
    <!ATTLIST Kapitel bewertung CDATA "1">

    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Termin (#PCDATA)>

  <!ELEMENT Quelle (Autor+,Titel)*>
    <!ATTLIST Quelle quellenID ID #REQUIRED>
    <!ATTLIST Quelle type (Monographie|Artikel|Dissertation|Abschlussarbeit) #REQUIRED>
    <!ELEMENT Autor (#PCDATA)>

=== beardeddragon5/internettechnologie/aufgabe2e.xml
<!DOCTYPE Vorlesung SYSTEM "vlml2.dtd">
<Vorlesung>
  <Titel>Programmieren</Titel>
  <Hochschule>HAW Landshut</Hochschule>
  <SWS>1</SWS>
  <Semester>Sommersemester</Semester>
  <?myTool align=left?>
  <!--  Anweisung an myTool -->
  <Kapitel nummer="1" quelle="Q1">
    <Name>Einf√ºhrung</Name>
    <Termin>1</Termin>
  </Kapitel>
  <Kapitel nummer="2" quelle="Q1">
    <Name>Datentypen</Name>
    <Termin>2</Termin>
  </Kapitel>
  <Kapitel nummer="3" quelle="Q1">
    <Name>Funktionen</Name>
    <Termin>3</Termin>
  </Kapitel>
  <Kapitel nummer="4" quelle="Q1">
    <Name>Pointer</Name>
    <Termin>4</Termin>
  </Kapitel>
  <Quelle quellenID="Q1" type="Artikel">
    <Autor>Ich</Autor>
    <Titel>Ein lustiges Buch</Titel>
  </Quelle>
</Vorlesung>
